# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Coindesk-API' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON'
  pod 'Alamofire'
  
  # Pods for Coindesk-API

  target 'Coindesk-APITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Coindesk-APIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
