# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Coindesk-API' do
  
  use_frameworks!
  pod 'SwiftyJSON'
  pod 'Alamofire'
  
  target 'Coindesk-APITests' do
    inherit! :search_paths
    pod 'SwiftyJSON'
  end

  target 'Coindesk-APIUITests' do
    inherit! :search_paths
    pod 'SwiftyJSON'
  end

end
